apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "github-credentials"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "Access to GitHub X-Celerate Repos"
type: Opaque
stringData:
  username: ""
  password: ""
