kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: build
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: build
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io